# Use Node.js base image
FROM node:16

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and flush_chats.js
COPY package.json flush_chats.js ./

# Install dependencies
RUN npm install mongoose redis

# Run the script
CMD [ "node", "flush_chats.js" ]